set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J23} [get_ports {J7_B[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H24} [get_ports {J7_B[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN L23} [get_ports {J7_B[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K23} [get_ports {J7_B[3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G24} [get_ports {J7_B[4]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F24} [get_ports {J7_B[5]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F23} [get_ports {J7_B[6]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E23} [get_ports {J7_B[7]}]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M19} [get_ports {J7_G[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN C24} [get_ports {J7_G[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN C22} [get_ports {J7_G[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN N21} [get_ports {J7_G[3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M21} [get_ports {J7_G[4]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN L22} [get_ports {J7_G[5]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN K22} [get_ports {J7_G[6]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN J21} [get_ports {J7_G[7]}]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN H22} [get_ports {J7_R[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN G22} [get_ports {J7_R[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN F22} [get_ports {J7_R[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN E21} [get_ports {J7_R[3]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D21} [get_ports {J7_R[4]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN N19} [get_ports {J7_R[5]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P20} [get_ports {J7_R[6]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN P21} [get_ports {J7_R[7]}]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R22} [get_ports {J7_CC[0]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN T22} [get_ports {J7_CC[1]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN R21} [get_ports {J7_CC[2]}]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN T20} [get_ports {J7_CC[3]}]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN U20} [get_ports J7_LVAL]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN T18} [get_ports J7_FVAL]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN M20} [get_ports J7_DVAL]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN D23} [get_ports J7_PCLK]

set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN T19} [get_ports J7_DTX]
set_property -dict { IOSTANDARD LVCMOS33 PACKAGE_PIN U19} [get_ports J7_DRX]
