set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN D10} [get_ports PCIE_RESET_N]
set_property PACKAGE_PIN D6 [get_ports PCIE_CLK_P]
set_property PACKAGE_PIN A4 [get_ports {PCIE_TX_P[0]}]
set_property PACKAGE_PIN B2 [get_ports {PCIE_TX_P[1]}]
set_property PACKAGE_PIN D2 [get_ports {PCIE_TX_P[2]}]
set_property PACKAGE_PIN F2 [get_ports {PCIE_TX_P[3]}]
set_property PACKAGE_PIN B6 [get_ports {PCIE_RX_P[0]}]
set_property PACKAGE_PIN C4 [get_ports {PCIE_RX_P[1]}]
set_property PACKAGE_PIN E4 [get_ports {PCIE_RX_P[2]}]
set_property PACKAGE_PIN G4 [get_ports {PCIE_RX_P[3]}]
